### ISSUE TITLE
A few more to highlight please?

### ISSUE THREAD

**Issue by ArgoCompass** [steebn/WebFOCUS-VSCode#2]
First, I just want to say "Thank you" for this.  I am new to WebFOCUS, and have spent all day looking for a good editor.  Your syntax highlighting is the best I have found BY FAR.  So thank you so much.

As I said, I am new to this, but a few items in my code that would be great to add to the list of those highlighted:
**-QUIT**
**PAGE** and **NOLEAD**  (ex. ON TABLE SET PAGE NOLEAD)

And finally, some of our coders use **$** to continue a command on a new line.  It would be nice to have that something other than white Ex:
ON TABLE SET STYLE *
TYPE=SUBFOOT,HEADALIGN=BODY,STYLE=BOLD,**$**  
TYPE=SUBFOOT,ITEM=4,HEADALIGN=BODY,JUSTIFY=RIGHT,STYLE=BOLD,**$**  
TYPE=SUBFOOT,ITEM=3,HEADALIGN=BODY,JUSTIFY=RIGHT,STYLE=BOLD,**$**  
ENDSTYLE

I hope this is helpful.  I would be happy to let you know if I find anything else as I go through code.  Again, thanks so much!

-AC

**Comment by steebn** [comment]
Thank you for the feedback. I will add this items to the syntax highlighting. I am currently working on some new styling snippets that I hope to publish by Monday Oct 1. I will add your requested highlights to this.

I really appreciate the extra set of eyes. Please let me know of any more that you come across.

**Comment by steebn** [comment]
I have published the updates that you suggested.  Let me know what other changes you would like to see.
